### ISSUE TITLE
Evaluate your model on ICDAR 2019 Modern datasets

### ISSUE THREAD

**Issue by Kehindeajayi01** [ejlee95/Graph-based-TSR#1]
Hi,
First, thanks for making your great work available to the public. I am trying to used your model to generate table structures for the ICDAR 2019 so that I can evaluate your model performance on the dataset but I don't seem to understand which file to run. Also, the input arguments to the model? Any pre-trained model to download and any other information that may be helpful for me to run your model will be highly appreciated.

Thanks

**Comment by ejlee95** [comment]
Hi Kehindeajayi01, thanks for your interest.
The main python file is code_training/main.py (both training and test),
and checkpoint files are in codes/experiments/bordered.
The execution command is written in README, so please refer to 'Execution - Test' part in README.md.


Please let me know if you have any further issues.

Thanks.

**Comment by Kehindeajayi01** [comment]
> Hi Kehindeajayi01, thanks for your interest. The main python file is code_training/main.py (both training and test), and checkpoint files are in codes/experiments/bordered. The execution command is written in README, so please refer to 'Execution - Test' part in README.md.
> 
> Please let me know if you have any further issues.
> 
> Thanks.

Thanks for your reply. Can the pointed file generate the xml structures for the ICDAR 2019 TrackB2 Modern datasets? This way I can evaluate the generated predictions against the ground truth.

**Comment by ejlee95** [comment]
Yes, the code generate xml file. But the generated XML file don't have content, just the structure of the table.

**Comment by Kehindeajayi01** [comment]
> Yes, the code generate xml file. But the generated XML file don't have content, just the structure of the table.

I am running into package error. Would it not be better to write a requirements.txt file as there are many packages you used than what you listed as the dependencies

**Comment by ejlee95** [comment]
I uploaded yml file having packages, please refer to readme.md.

**Comment by Kehindeajayi01** [comment]
> I uploaded yml file having packages, please refer to readme.md.

I got the following error about licence for Gurobi::

<img width="810" alt="Screen Shot 2022-02-11 at 3 22 56 PM" src="https://user-images.githubusercontent.com/43017928/153898248-763cbafd-1d4f-43eb-a949-81e622af8a00.png">

**Comment by ejlee95** [comment]
I think you should either buy a Gurobi license, or (if you are in school) use an academic license.
I'm sorry that I couldn't help you.

**Comment by Kehindeajayi01** [comment]
> I think you should either buy a Gurobi license, or (if you are in school) use an academic license. I'm sorry that I couldn't help you.

It worked. Thanks so much
