### ISSUE TITLE
Custom training data

### ISSUE THREAD

**Issue by CrazyCrud** [ejlee95/Graph-based-TSR#2]
Hello,
first of all, thank you for your work and for publishing the code!     

I was wondering how custom training data can be generated and which tools you used to generate the training data based on the ICDAR2019 ground truth?    

Best regards,
Constantin

**Comment by ejlee95** [comment]
First, the training data is the subset of ICDAR2019 training data; the images are from open benchmarks, and we annotated junctions for our own.
For labeling, we wrote the python code using opencv library to localize the junctions, not using the given ground truth annotations.
But it's hard to distribute the code for now, the code might be released in the future.

Sincerely,
Eunji

**Comment by CrazyCrud** [comment]
@ejlee95 thank you very much for your answer.
